spring:
  application:
    name: APIGetway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: lb://customer-service
            predicates:
              - Path=/api/v0/customers/**

          - id: item-service
            uri: lb://item-service
            predicates:
              - Path=/api/v0/item/**

server:
  port: 8084
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  servlet:
    context-path: /app
